"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class armStatus_t(object):
    __slots__ = ["jointPosition", "jointVelocity", "jointCurrent", "jointStatus"]

    __typenames__ = ["double", "double", "double", "double"]

    __dimensions__ = [[7], [7], [7], [7]]

    def __init__(self):
        self.jointPosition = [ 0.0 for dim0 in range(7) ]
        self.jointVelocity = [ 0.0 for dim0 in range(7) ]
        self.jointCurrent = [ 0.0 for dim0 in range(7) ]
        self.jointStatus = [ 0.0 for dim0 in range(7) ]

    def encode(self):
        buf = BytesIO()
        buf.write(armStatus_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>7d', *self.jointPosition[:7]))
        buf.write(struct.pack('>7d', *self.jointVelocity[:7]))
        buf.write(struct.pack('>7d', *self.jointCurrent[:7]))
        buf.write(struct.pack('>7d', *self.jointStatus[:7]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != armStatus_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return armStatus_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = armStatus_t()
        self.jointPosition = struct.unpack('>7d', buf.read(56))
        self.jointVelocity = struct.unpack('>7d', buf.read(56))
        self.jointCurrent = struct.unpack('>7d', buf.read(56))
        self.jointStatus = struct.unpack('>7d', buf.read(56))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if armStatus_t in parents: return 0
        tmphash = (0xa8e2a691d4c4e420) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if armStatus_t._packed_fingerprint is None:
            armStatus_t._packed_fingerprint = struct.pack(">Q", armStatus_t._get_hash_recursive([]))
        return armStatus_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", armStatus_t._get_packed_fingerprint())[0]

